In [2]:
import numpy as np

print(np.__version__)

1.24.3


In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
np.ones([2,2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

In [9]:
np.ones([3,2], dtype='f')

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

In [16]:
X = np.arange(4, dtype='i')
np.ones_like(X)

array([1, 1, 1, 1], dtype=int32)

In [17]:
X = np.array([[1,2,3],[4,5,6]], dtype=int)
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]])

In [18]:
np.ones([4,4], dtype=int) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [20]:
X = np.array([[2,3], [6,2]], dtype=np.int8)
np.ones_like(X) * 7

array([[7, 7],
       [7, 7]], dtype=int8)

In [21]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.random.default_rng().integers(10, size=3)


array([6, 0, 2])

In [32]:
np.random.randn(3,3,3)

array([[[-1.31041081,  1.17311676,  1.78367638],
        [-0.44097259, -1.32779796,  1.22596674],
        [-0.85028775, -0.16576135, -1.10590371]],

       [[ 0.2491735 , -0.53155289,  0.10762625],
        [ 0.22035187,  1.48597322, -0.06366361],
        [ 0.02931425,  0.656421  ,  0.04135927]],

       [[ 0.35466685,  0.18838238,  1.3591592 ],
        [ 0.63123863, -1.06875556,  2.24838268],
        [ 1.78725895, -1.30056891, -0.53614319]]])

In [33]:
X = [1,2,3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [34]:
X = np.array([5,2,3], dtype=np.int8)
Y = np.copy(X)
print(id(X), id(Y))

139995806202928 139995806197360


In [35]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
np.arange(1,11, 2)

array([1, 3, 5, 7, 9])

In [37]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [38]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


In [39]:
X = np.array(['a','b'])
X[0]

'a'

In [40]:
X = np.array(['A','B','C','D','E'])
X[-1]

'E'

In [41]:
X = np.array(['A','B','C','D','E'])
X[:3]

array(['A', 'B', 'C'], dtype='<U1')

In [42]:
X = np.array(['A','B','C','D','E'])
X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

In [43]:
X = np.array(['A','B','C','D','E'])
X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

In [45]:
X = np.array(['A','B','C','D','E'])
X[::2]

array(['A', 'C', 'E'], dtype='<U1')

In [46]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

In [47]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

In [48]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

#X[0][0]
X[0, 0]

1

In [49]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1,-1]

16

In [50]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

In [51]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[:2,:2]

array([[1, 2],
       [5, 6]])

In [52]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:,2:]

array([[11, 12],
       [15, 16]])

In [54]:
X = [-5, -3, 0, 10, 40]
np.array(X, np.float32)

array([-5., -3.,  0., 10., 40.], dtype=float32)

In [55]:
X = [-5, -3, 0, 10, 40]
X[::-1]

[40, 10, 0, -3, -5]

In [57]:
X = [0, 10, -5, 40, -3]
X.sort()
X

[-5, -3, 0, 10, 40]

In [58]:
X = np.zeros(10)

X[4] = 1
X


array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [59]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X[-1] = np.array([1,1,1,1])

In [60]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [61]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

In [6]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
mask = X > 5
X[mask]

array([ 6, 10])

In [7]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X[X > X.mean()]

array([ 2,  5,  6, 10])

In [9]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X[(X==2) | (X==10)]

array([ 2, 10])

In [10]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.all()

False

In [11]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.any()

True

In [12]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X.sum()

43

In [13]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.mean()

3.7

In [14]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.sum(axis=0)

array([28, 32, 36, 40])

In [15]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X.mean(axis=1) 

array([ 2.5,  6.5, 10.5, 14.5])

In [16]:
X = np.array([1, 2, 0, 4, 5, 6, 0, 0, 9, 10])
X.max()

10